insert into item values ( 1, null, 'B'    , 2);
insert into item values (12,    1, 'B 2'  , 2);
insert into item values ( 9, null, 'C'    , 3);
insert into item values ( 4,    1, 'B 3'  , 3);
insert into item values (16,    1, 'B 1'  , 1);
insert into item values ( 2,    9, 'C 2'  , 2);
insert into item values ( 7, null, 'A'    , 1);
insert into item values ( 6,    9, 'C 1'  , 1);
insert into item values (10,    6, 'C 1 a', 1);
insert into item values (27,   12, 'B 2 c', 3);
insert into item values (15,   16, 'B 1 b', 2);
insert into item values (23,    7, 'A 2'  , 2);
insert into item values (20,    6, 'C 1 b', 2);
insert into item values ( 5,   12, 'B 2 a', 1);
insert into item values (19,    7, 'A 1'  , 1);
insert into item values (13,    7, 'A 3'  , 3);
insert into item values ( 3,   12, 'B 2 b', 2);
insert into item values (14,   16, 'B 1 a', 1);
insert into item values (11,   16, 'B 1 c', 3);
